# Site settings
author: Ranika Williams
title: Life + Development
header-img: img/home-bg.png
email: rnkprice07@gmail.com
copyright_name: Ranika Williams
description: > # this means to ignore newlines until "baseurl:"
  Journey into learning code.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  rnkwilliams

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
